# Generated by Django 5.0 on 2024-01-03 18:26

import Booking.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[Booking.models.Reservation.reservation_date_validator]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(default=Booking.models.Reservation.next_hour, validators=[Booking.models.Reservation.reservation_time_validator]),
        ),
    ]
