# Generated by Django 5.0 on 2024-01-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('reservation_date', 'reservation_time')},
        ),
    ]
