# Generated by Django 5.0 on 2024-01-04 01:36

import Booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'reservation_time']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=Booking.models.Reservation.current_dt, validators=[Booking.models.Reservation.reservation_date_validator]),
        ),
    ]
