# Generated by Django 5.0 on 2023-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0002_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='featured',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
