# Generated by Django 5.0 on 2023-12-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0003_remove_menuitem_featured_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='origin',
            field=models.CharField(default='origin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='varietal',
            field=models.CharField(default='varietal', max_length=255),
            preserve_default=False,
        ),
    ]
