# Generated by Django 5.0 on 2024-01-02 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0004_menuitem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
