# Generated by Django 5.0 on 2024-01-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0005_alter_menuitem_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('R', 'Received'), ('P', 'Processing'), ('S', 'Shipped')], default='R', max_length=1),
        ),
    ]
