# Generated by Django 5.0.1 on 2024-01-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0008_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
