# Generated by Django 5.0.1 on 2024-01-31 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='milk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TeaAPI.milk'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemcategory',
            unique_together={('category', 'menuitem')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem', 'milk')},
        ),
    ]
