# Generated by Django 5.0.1 on 2024-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0003_milk_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
