# Generated by Django 5.0.1 on 2024-02-07 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0004_remove_order_total_remove_orderitem_line_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menuitem', 'milk', 'user')},
        ),
    ]
