# Generated by Django 5.0.1 on 2024-03-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0006_temperature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='temperature',
            field=models.CharField(choices=[('H', 'Hot'), ('I', 'Iced')], default='I', max_length=1),
        ),
    ]
