# Generated by Django 5.0.1 on 2024-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0007_delete_temperature_menuitem_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='temperature',
            field=models.CharField(default='H', max_length=1),
        ),
    ]
