# Generated by Django 5.0.1 on 2024-03-28 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0008_cart_temperature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menuitem', 'milk', 'user', 'temperature')},
        ),
    ]
