# Generated by Django 5.0.1 on 2024-03-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0009_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='temperature',
            field=models.CharField(choices=[('N', 'Not Changable'), ('H', 'Hot'), ('I', 'Iced')], default='I', max_length=1),
        ),
    ]
