# Generated by Django 5.0.1 on 2024-03-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0010_alter_menuitem_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='temperature',
            field=models.CharField(default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='temperature',
            field=models.CharField(choices=[('N', 'Iced - Not Changable'), ('X', 'Hot - Not Changable'), ('H', 'Hot'), ('I', 'Iced')], default='I', max_length=1),
        ),
    ]
