# Generated by Django 5.0.1 on 2024-04-01 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0012_alter_menuitem_temperature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='sweetness',
            field=models.CharField(default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sweetness',
            field=models.CharField(choices=[('N', 'Not Changable'), ('100', '100%'), ('75', '75%'), ('50', '50%'), ('25', '25%'), ('0', '0%')], default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sweetness',
            field=models.CharField(default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='temperature',
            field=models.CharField(default='I', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menuitem', 'milk', 'user', 'temperature', 'sweetness')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem', 'milk', 'temperature', 'sweetness')},
        ),
    ]
