# Generated by Django 5.0.1 on 2024-10-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaAPI', '0014_remove_menuitem_categories_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
